language: go

go:
  - 1.13.x

go_import_path: github.com/aQuaYi/jili

# whitelist
branches:
  only:
  - master
  - stable

script:
  - go get -t -v ./...
  - go vet ./...
  - bash ./scripts/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)